// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization/GreeterActorProtocol.proto

package com.akka.sample.serialization.models.greet;

public final class GreeterActorProtocol {
  private GreeterActorProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Greet)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Greet}
   */
  public  static final class Greet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Greet)
      GreetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Greet.newBuilder() to construct.
    private Greet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Greet() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Greet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_Greet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_Greet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.class, com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet)) {
        return super.equals(obj);
      }
      com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet other = (com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Greet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Greet)
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.GreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_Greet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_Greet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.class, com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.Builder.class);
      }

      // Construct using com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_Greet_descriptor;
      }

      @java.lang.Override
      public com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet getDefaultInstanceForType() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.getDefaultInstance();
      }

      @java.lang.Override
      public com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet build() {
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet buildPartial() {
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet result = new com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet) {
          return mergeFrom((com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet other) {
        if (other == com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Greet)
    }

    // @@protoc_insertion_point(class_scope:Greet)
    private static final com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet();
    }

    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Greet>
        PARSER = new com.google.protobuf.AbstractParser<Greet>() {
      @java.lang.Override
      public Greet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Greet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Greet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Greet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.akka.sample.serialization.models.greet.GreeterActorProtocol.Greet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WhoToGreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WhoToGreet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string who = 1;</code>
     */
    java.lang.String getWho();
    /**
     * <code>string who = 1;</code>
     */
    com.google.protobuf.ByteString
        getWhoBytes();
  }
  /**
   * Protobuf type {@code WhoToGreet}
   */
  public  static final class WhoToGreet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WhoToGreet)
      WhoToGreetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WhoToGreet.newBuilder() to construct.
    private WhoToGreet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WhoToGreet() {
      who_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WhoToGreet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              who_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_WhoToGreet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_WhoToGreet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.class, com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.Builder.class);
    }

    public static final int WHO_FIELD_NUMBER = 1;
    private volatile java.lang.Object who_;
    /**
     * <code>string who = 1;</code>
     */
    public java.lang.String getWho() {
      java.lang.Object ref = who_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        who_ = s;
        return s;
      }
    }
    /**
     * <code>string who = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWhoBytes() {
      java.lang.Object ref = who_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        who_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWhoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, who_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWhoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, who_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet)) {
        return super.equals(obj);
      }
      com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet other = (com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet) obj;

      boolean result = true;
      result = result && getWho()
          .equals(other.getWho());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WHO_FIELD_NUMBER;
      hash = (53 * hash) + getWho().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WhoToGreet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WhoToGreet)
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_WhoToGreet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_WhoToGreet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.class, com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.Builder.class);
      }

      // Construct using com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        who_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.internal_static_WhoToGreet_descriptor;
      }

      @java.lang.Override
      public com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet getDefaultInstanceForType() {
        return com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.getDefaultInstance();
      }

      @java.lang.Override
      public com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet build() {
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet buildPartial() {
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet result = new com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet(this);
        result.who_ = who_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet) {
          return mergeFrom((com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet other) {
        if (other == com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet.getDefaultInstance()) return this;
        if (!other.getWho().isEmpty()) {
          who_ = other.who_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object who_ = "";
      /**
       * <code>string who = 1;</code>
       */
      public java.lang.String getWho() {
        java.lang.Object ref = who_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          who_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string who = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWhoBytes() {
        java.lang.Object ref = who_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          who_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string who = 1;</code>
       */
      public Builder setWho(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        who_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string who = 1;</code>
       */
      public Builder clearWho() {
        
        who_ = getDefaultInstance().getWho();
        onChanged();
        return this;
      }
      /**
       * <code>string who = 1;</code>
       */
      public Builder setWhoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        who_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WhoToGreet)
    }

    // @@protoc_insertion_point(class_scope:WhoToGreet)
    private static final com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet();
    }

    public static com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WhoToGreet>
        PARSER = new com.google.protobuf.AbstractParser<WhoToGreet>() {
      @java.lang.Override
      public WhoToGreet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WhoToGreet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WhoToGreet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WhoToGreet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.akka.sample.serialization.models.greet.GreeterActorProtocol.WhoToGreet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Greet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Greet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WhoToGreet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WhoToGreet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(serialization/GreeterActorProtocol.pro" +
      "to\"\007\n\005Greet\"\031\n\nWhoToGreet\022\013\n\003who\030\001 \001(\tB," +
      "\n*com.akka.sample.serialization.models.g" +
      "reetb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Greet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Greet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Greet_descriptor,
        new java.lang.String[] { });
    internal_static_WhoToGreet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WhoToGreet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WhoToGreet_descriptor,
        new java.lang.String[] { "Who", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
